.isr reset TEST_ENTRY
.org 0x2000

TEST_ENTRY:
    LDA #$30
    STA TTY_SER0_REGISTER_FIFO
    LDA #$31
    STA TTY_SER0_REGISTER_FIFO
    LDA #$00
    STA TTY_SER0_REGISTER_FIFO

FLUSH:
    LDA TTY_SER0_REGISTER_OUT_COUNT
    BNE FLUSH

    HLT #$00

